const AUDIENCE_OPTIONS = {
	// FILM_GET: "FILM_GET",
	// USERS_GET: "USERS_GET",
	// CUSTOMERS_GET: "CUSTOMERS_GET",
	// CUSTOMERS_SEARCH: "CUSTOMERS_SEARCH",
	// ACTOR_SEARCH: "ACTOR_SEARCH",
	// FILM_SEARCH: "FILM_SEARCH",
	// ACTOR_ADD: "ACTOR_ADD",
	// ACTOR_UPDATE: "ACTOR_UPDATE",
	// ACTOR_DELETE: "ACTOR_DELETE",
	// FILM_ADD: "FILM_ADD",
	// FILM_UPDATE: "FILM_UPDATE",
	// FILM_DELETE: "FILM_DELETE",
	EMPLOYEE_DETAILS: "EMPLOYEE_DETAILS",
	FILE_REIMBURSEMENT: "FILE_REIMBURSEMENT",
	ADD_REIMB_TRANSACTION: "ADD_REIMB_TRANSACTION",
};

// const CUSTOMER_AUDIENCE = [
// 	AUDIENCE_OPTIONS.ACTOR_SEARCH,
// 	AUDIENCE_OPTIONS.FILM_SEARCH,
// ];
// const STAFF_AUDIENCE = [
// 	...CUSTOMER_AUDIENCE,
// 	AUDIENCE_OPTIONS.FILM_GET,
// 	AUDIENCE_OPTIONS.USERS_GET,
// 	AUDIENCE_OPTIONS.CUSTOMERS_GET,
// 	AUDIENCE_OPTIONS.CUSTOMERS_SEARCH,
// 	AUDIENCE_OPTIONS.ACTOR_ADD,
// 	AUDIENCE_OPTIONS.ACTOR_UPDATE,
// 	AUDIENCE_OPTIONS.ACTOR_DELETE,
// 	AUDIENCE_OPTIONS.FILM_ADD,
// 	AUDIENCE_OPTIONS.FILM_UPDATE,
// 	AUDIENCE_OPTIONS.FILM_DELETE,
// ];

const EMPLOYEE_AUDIENCE = [
	AUDIENCE_OPTIONS.EMPLOYEE_DETAILS,
	AUDIENCE_OPTIONS.FILE_REIMBURSEMENT,
	AUDIENCE_OPTIONS.ADD_REIMB_TRANSACTION,
];
const HR_AUDIENCE = [
	AUDIENCE_OPTIONS.EMPLOYEE_DETAILS,
	"TEST1",
	"TEST2",
	AUDIENCE_OPTIONS.FILE_REIMBURSEMENT,
	AUDIENCE_OPTIONS.ADD_REIMB_TRANSACTION,
];
const PAYROLL_AUDIENCE = [
	AUDIENCE_OPTIONS.EMPLOYEE_DETAILS,
	AUDIENCE_OPTIONS.FILE_REIMBURSEMENT,
	AUDIENCE_OPTIONS.ADD_REIMB_TRANSACTION,
];

const JWT_OPTIONS = {
	EMPLOYEE_AUDIENCE,
	HR_AUDIENCE,
	PAYROLL_AUDIENCE,
};

module.exports = {
	JWT_OPTIONS,
	AUDIENCE_OPTIONS,
};
