const audOpts = {
	EMPLOYEE_DETAILS: "EMPLOYEE_DETAILS",
	ADD_REIMB_TRANSACTION: "ADD_REIMB_TRANSACTION",
	FILE_REIMBURSEMENT_ITEM: "FILE_REIMBURSEMENT_ITEM",
	GET_REIMBURSEMENT_ITEM: "GET_REIMBURSEMENT_ITEM",
	GET_ALL_REIMBURSEMENT_ITEMS: "GET_ALL_REIMBURSEMENT_ITEMS",
	DELETE_REIMBURSEMENT_ITEM: "DELETE_REIMBURSEMENT_ITEM",
};

const EMPLOYEE_AUDIENCE = [
	audOpts.EMPLOYEE_DETAILS,
	audOpts.FILE_REIMBURSEMENT_ITEM,
	audOpts.ADD_REIMB_TRANSACTION,
	audOpts.GET_REIMBURSEMENT_ITEM,
	audOpts.GET_ALL_REIMBURSEMENT_ITEMS,
	audOpts.DELETE_REIMBURSEMENT_ITEM,
];
const HR_AUDIENCE = [...EMPLOYEE_AUDIENCE];
const PAYROLL_AUDIENCE = [...EMPLOYEE_AUDIENCE];

const JWT_OPTIONS = {
	EMPLOYEE_AUDIENCE,
	HR_AUDIENCE,
	PAYROLL_AUDIENCE,
};

module.exports = {
	JWT_OPTIONS,
	AUDIENCE_OPTIONS: audOpts,
};
