const AUDIENCE_OPTIONS = {
	FILM_GET: "FILM_GET",
	USERS_GET: "USERS_GET",
	CUSTOMERS_GET: "CUSTOMERS_GET",
	CUSTOMERS_SEARCH: "CUSTOMERS_SEARCH",
	ACTOR_SEARCH: "ACTOR_SEARCH",
	FILM_SEARCH: "FILM_SEARCH",
	ACTOR_ADD: "ACTOR_ADD",
	ACTOR_UPDATE: "ACTOR_UPDATE",
	ACTOR_DELETE: "ACTOR_DELETE",
	FILM_ADD: "FILM_ADD",
	FILM_UPDATE: "FILM_UPDATE",
	FILM_DELETE: "FILM_DELETE",
};

const CUSTOMER_AUDIENCE = [
	AUDIENCE_OPTIONS.ACTOR_SEARCH,
	AUDIENCE_OPTIONS.FILM_SEARCH,
];
const STAFF_AUDIENCE = [
	...CUSTOMER_AUDIENCE,
	AUDIENCE_OPTIONS.FILM_GET,
	AUDIENCE_OPTIONS.USERS_GET,
	AUDIENCE_OPTIONS.CUSTOMERS_GET,
	AUDIENCE_OPTIONS.CUSTOMERS_SEARCH,
	AUDIENCE_OPTIONS.ACTOR_ADD,
	AUDIENCE_OPTIONS.ACTOR_UPDATE,
	AUDIENCE_OPTIONS.ACTOR_DELETE,
	AUDIENCE_OPTIONS.FILM_ADD,
	AUDIENCE_OPTIONS.FILM_UPDATE,
	AUDIENCE_OPTIONS.FILM_DELETE,
];

const EMPLOYEE_AUDIENCE = [];
const HR_AUDIENCE = [];
const PAYROLL_AUDIENCE = [];

const JWT_OPTIONS = {
	CUSTOMER_AUDIENCE,
	STAFF_AUDIENCE,
	EMPLOYEE_AUDIENCE,
	HR_AUDIENCE,
	PAYROLL_AUDIENCE,
};

module.exports = {
	JWT_OPTIONS,
	AUDIENCE_OPTIONS,
};
